[package]
name = "router-client"
version = "0.1.0"
authors = ["de-user"]
build = "build.rs"

[build-dependencies]
serde_codegen = "0.8"

[dependencies]
error-chain = {version = "0.7"}
serde = {version = "0.8"}
serde_json = {version = "0.8"}
